ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

